# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_L
  - override /env: labyrinth
  - _self_

# Experiment
seed: 5

# Environment
env:
  id: Labyrinth3D-v0
  num_envs: 1


# Checkpoint
checkpoint:
  every: 10000
  resume_from: logs/runs/dreamer_v3/Labyrinth3D-v0/2025-02-28_15-54-22_dreamer_v3_Labyrinth3D-v0_5/version_0/checkpoint/ckpt_100000_0.ckpt

# Algorithm
algo:
  total_steps: 150000
  learning_starts: 0
  cnn_keys:
    encoder:
      - image
    decoder:
      - image
  mlp_keys:
    encoder:
      - states
      - targets
      - progress
    decoder:
      - states
      - targets
      - progress

# Metric
metric:
  log_every: 10000

fabric:
  accelerator: cuda
  precision: bf16-mixed