# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_L
  - override /env: labyrinth
  - _self_

# Experiment
seed: 5

# Environment
env:
  id: Labyrinth3D-v0
  num_envs: 2
  wrapper:
    n_envs: 2


# Checkpoint
checkpoint:
  every: 4000

# Algorithm
algo:
  total_steps: 120000
  learning_starts: 8000
  cnn_keys:
    encoder:
      - image
    decoder:
      - image
  mlp_keys:
    encoder:
      - states
      - targets
      - progress
    decoder:
      - states
      - targets
      - progress

# Metric
metric:
  log_every: 8000

fabric:
  devices: -1
  accelerator: gpu